version: 2
jobs:
  build:
    working_directory: ~/mulog-transit-file-publisher
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.0.442
    steps:
      - checkout
      - run: clj -e "(compile 'ifarafontov.NoopFlushOutputStream)" 
      - run: ./run-tests.sh